version: '3.8'

services:
  php56:
    build: .
    container_name: php56_app
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    environment:
      - DB_HOST=mysql             
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=rickAndMorty    
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql57_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rickAndMorty
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports: 
      - "3307:3306"
    volumes: 
      - db_data:/var/lib/mysql

volumes:
  db_data:
